## Timing Constraints for Matrix Multiply Accelerator
## Target: 100 MHz (10 ns period)

## Primary clock (defined in arty_a7_35t.xdc)
## create_clock -period 10.000 -name clk [get_ports S_AXI_ACLK]

## Input delay constraints (from AXI interconnect)
## set_input_delay -clock clk -max 2.0 [get_ports S_AXI_*]
## set_input_delay -clock clk -min 0.5 [get_ports S_AXI_*]

## Output delay constraints
## set_output_delay -clock clk -max 2.0 [get_ports S_AXI_*]

## Note: When integrating into a MicroBlaze block design,
## timing constraints are automatically generated by Vivado.
## These manual constraints are for standalone synthesis only.

